In [1]:
import os, numpy as np
import pandas as pd

os.environ["KERAS_BACKEND"] = "tensorflow"

import keras 
from sklearn import datasets

from sklearn.model_selection import train_test_split

from keras.utils import np_utils


def set_reproducible():
    import tensorflow as tf
    import random as rn
    import os
    os.environ['PYTHONHASHSEED'] = '1960'
    rn.seed(1960)
    np.random.seed(1960)
    session_conf = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)

    from keras import backend as K
    tf.set_random_seed(1960)

    sess = tf.Session(graph=tf.get_default_graph(), config=session_conf)
    K.set_session(sess)

set_reproducible()

Using TensorFlow backend.

# Build a Keras Model

In [2]:
NC = 13

def create_model():
    from keras.models import Sequential
    from keras.layers import Dense, Activation, SimpleRNN
    from keras.constraints import max_norm

    model = Sequential()
    model.add(SimpleRNN(4, input_shape=(1, NC), batch_size=1 , 
                   activation='relu',
                   stateful=True,
                   kernel_constraint=max_norm(2.),
                   recurrent_constraint=max_norm(2.),
                   kernel_initializer = keras.initializers.Orthogonal(gain=0.1),
                   recurrent_initializer = keras.initializers.Zeros()))
    model.add(Dense(1, activation=None))
    adam_optimizer = keras.optimizers.Adam(lr=0.01, clipnorm=1.)
    model.compile(loss='mse', optimizer=adam_optimizer)
    return model

In [3]:
boston  = datasets.load_boston()
boston.data = (boston.data - boston.data.mean(axis=0)) / boston.data.std(axis=0)
boston.target = (boston.target - boston.target.mean(axis=0)) / boston.target.std(axis=0)

boston.data = boston.data[:,0:NC]

train_X, test_X, train_y, test_y = train_test_split(boston.data, boston.target, train_size=0.6, test_size=0.4, random_state=1960)
train_X = train_X.reshape(train_X.shape[0] , 1, train_X.shape[1])
test_X = test_X.reshape(test_X.shape[0] , 1, test_X.shape[1])

In [4]:
#boston.data

In [5]:
#boston.target

In [6]:

from keras.wrappers.scikit_learn import KerasRegressor

clf = KerasRegressor(build_fn=create_model, batch_size=1, epochs=12, verbose=2)

print(train_X.shape , train_y.shape)
clf.fit(train_X, train_y)

(303, 1, 13) (303,)
Epoch 1/12
 - 1s - loss: 0.4711
Epoch 2/12
 - 1s - loss: 0.3619
Epoch 3/12
 - 1s - loss: 0.3652
Epoch 4/12
 - 1s - loss: 0.3253
Epoch 5/12
 - 1s - loss: 0.3464
Epoch 6/12
 - 1s - loss: 0.2967
Epoch 7/12
 - 1s - loss: 0.3313
Epoch 8/12
 - 1s - loss: 0.2875
Epoch 9/12
 - 1s - loss: 0.3359
Epoch 10/12
 - 1s - loss: 0.3890
Epoch 11/12
 - 1s - loss: 0.3626
Epoch 12/12
 - 1s - loss: 0.3147

In [7]:
print(test_X.shape)
preds = clf.predict(test_X)
print(preds)

(203, 1, 13)
[-1.06120348e-01 -4.68807876e-01 -4.19324756e-01 -4.59029377e-01
  2.38383055e-01 -4.70850110e-01 -6.76228285e-01 -4.40464437e-01
 -1.31780505e+00 -5.03729522e-01 -5.03729522e-01 -6.33671165e-01
 -1.28899515e-02 -1.23498559e+00  1.25148702e+00 -2.08488584e-01
  1.36989331e+00  6.90436542e-01 -5.98816991e-01  5.51429927e-01
 -2.62875915e-01  2.03246975e+00 -5.30728638e-01  1.37380576e+00
  1.46294975e+00 -3.68447244e-01 -2.26225793e-01 -1.64742470e+00
  4.29284513e-01 -1.16125429e+00  9.77003872e-01 -7.53580868e-01
 -5.03729522e-01  1.42702079e+00  4.21265841e-01  1.23010516e-01
  4.62387621e-01 -8.37476552e-01 -9.24494386e-01  7.37173975e-01
 -4.90710199e-01 -1.69981688e-01 -6.16247833e-01 -7.21296251e-01
 -3.55155647e-01 -4.75190878e-02  3.66675198e-01 -1.81154400e-01
 -1.55375600e+00 -3.06081057e-01 -3.17018002e-01 -6.35816753e-01
 -1.70518827e+00  1.57954049e+00  3.34363043e-01 -5.03729522e-01
  1.16390085e+00  1.02061152e-01  8.46289396e-02 -1.88797712e-02
 -1.32567495e-01  1.41195655e+00 -2.05040991e-01 -3.24883759e-02
 -1.85887766e+00  1.53332567e+00  1.87790930e-01 -5.03729522e-01
 -1.42019081e+00  7.82607615e-01  4.29018319e-01  1.26487303e+00
  3.48071158e-01  4.52250242e-03 -8.85210335e-02 -5.03729522e-01
  1.85657120e+00  4.38153744e-01 -5.03729522e-01  1.15199232e+00
 -4.69006777e-01  2.31448352e-01  2.02463567e-01 -5.03729522e-01
 -8.34146380e-01  6.03212655e-01 -5.03729522e-01  1.34369469e+00
 -3.65284383e-01  1.25875306e+00 -1.59821606e+00  1.49702787e+00
  5.85290253e-01 -5.03729522e-01  3.18795443e-02 -1.26752913e-01
  8.73898923e-01  1.23638964e+00 -2.84778774e-02 -3.34905893e-01
  1.94498599e-01 -6.97187483e-01  7.12779343e-01 -3.95073891e-02
 -2.68610388e-01 -2.90031433e-01 -5.03729522e-01 -8.82875085e-01
  1.59884715e+00 -2.50802827e+00  1.83102250e+00  4.80271637e-01
  2.84228861e-01  1.45191908e+00 -8.27453434e-01  3.12789857e-01
 -9.92014766e-01 -5.03729522e-01 -1.69966507e+00  3.18994582e-01
  9.31900740e-02 -8.27716708e-01 -1.43403351e+00 -5.03729522e-01
 -6.19883657e-01  1.10123873e+00 -9.73415434e-01  9.56493318e-01
 -5.11771142e-01 -5.03729522e-01 -5.02424419e-01 -1.95939481e-01
  8.70078862e-01 -1.23244524e-03 -5.03729522e-01 -1.25008559e+00
  1.04429817e+00  3.81432176e-02 -9.44606662e-02 -1.37315798e+00
 -5.03729522e-01  2.34063935e+00 -2.17641890e-01 -5.03729522e-01
  4.47343171e-01  2.99256384e-01 -2.80859888e-01  2.95482874e-02
  1.23025823e+00 -5.23578525e-02 -5.03729522e-01  2.28536606e-01
  1.27393627e+00  5.10918081e-01 -5.03729522e-01 -1.39558291e+00
  2.03769517e+00  8.82318795e-01 -5.02613902e-01 -7.89804101e-01
  3.45863342e-01 -8.49558055e-01  1.51007414e-01 -8.10478985e-01
  9.02010024e-01  5.44182599e-01 -5.03729522e-01  3.33017135e+00
  3.51759851e-01  1.06973529e+00 -4.48310375e-03 -8.34502280e-02
 -2.96590418e-01 -1.10405540e+00 -3.09886098e-01 -2.41992414e-01
 -3.46414745e-01 -1.68882668e-01 -1.94637835e-01  6.63156509e-02
 -7.12047756e-01  2.12901378e+00  1.37568784e+00 -2.97715545e-01
  1.03110170e+00  3.36698890e-02  3.66422415e-01  1.71695399e+00
 -7.31131434e-01  7.21866786e-01  1.65279579e+00  6.94118083e-01
 -7.61720598e-01  3.87199759e-01  5.82721174e-01  1.23525858e+00
  3.28283370e-01  7.95180142e-01  1.60804009e+00 -5.83230495e-01
 -4.65209961e-01  4.73917723e-01 -8.24505210e-01]

# Generate SQL Code from the Model

In [8]:
import json, requests, base64, dill as pickle, sys



sys.setrecursionlimit(200000)
pickle.settings['recurse'] = False

# no luck for the web service... pickling feature of tensorflow and/or keras objects seems not to be a priority.
# there is a lot of github issues in the two projects when I search for pickle keyword!!!.

def test_ws_sql_gen(pickle_data):
    WS_URL="http://localhost:1888/model"
    b64_data = base64.b64encode(pickle_data).decode('utf-8')
    data={"Name":"model1", "PickleData":b64_data , "SQLDialect":"postgresql"}
    r = requests.post(WS_URL, json=data)
    print(r.__dict__)
    content = r.json()
    # print(content)
    lSQL = content["model"]["SQLGenrationResult"][0]["SQL"]
    return lSQL;



def test_sql_gen(keras_regressor , metadata):
    import sklearn2sql.PyCodeGenerator as codegen
    cg1 = codegen.cAbstractCodeGenerator();
    cg1.mOptions.mActivateMaterialization = False
    lSQL = cg1.generateCodeWithMetadata(clf, metadata, dsn = None, dialect = "postgresql");
    return lSQL[1]

In [9]:
# commented .. see above
# pickle_data = pickle.dumps(clf)
# lSQL = test_ws_sql_gen(pickle_data)
# print(lSQL[0:2000])

In [10]:
lMetaData = {}
lMetaData['features'] = list(boston.feature_names);
lMetaData["targets"] = ['TGT']
lMetaData['primary_key'] = 'KEY'
lMetaData['table'] = 'boston'

    
lSQL = test_sql_gen(clf , lMetaData)

cGenerationWrapperFactory::createWrapper() <class 'keras.wrappers.scikit_learn.KerasRegressor'>
BACKEND_DIALECT postgresql
CREATING_DATABASE_BACKEND_DSN_DIALECT 1.2.7 None postgresql
KERAS_REG_GENERATE_EXPRESSION_START <class 'sqlalchemy.sql.selectable.Alias'> <class 'sklearn2sql.GenericModels.Keras.cSerializedKeras'>
{'mKerasData': <keras.wrappers.scikit_learn.KerasRegressor object at 0x7ff1e73286a0>, 'mFeatureNames': ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'], 'mClasses': None, 'mMode': 'Regression'}
{'build_fn': <function create_model at 0x7ff1e730f9d8>, 'sk_params': {'batch_size': 1, 'epochs': 12, 'verbose': 2}, 'model': <keras.engine.sequential.Sequential object at 0x7ff1e7328710>}
GENERATING_LAYER 0 simple_rnn_1 <class 'keras.layers.recurrent.SimpleRNN'> {'input_spec': [InputSpec(shape=(1, None, 13), ndim=3)], 'supports_masking': True, 'stateful': True, '_trainable_weights': [], '_non_trainable_weights': [], '_losses': [], '_updates': [(<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 4) dtype=float32_ref>, <tf.Tensor 'simple_rnn_1/while/Exit_3:0' shape=(1, 4) dtype=float32>)], '_per_input_losses': {}, '_per_input_updates': {'140676942695168': [(<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 4) dtype=float32_ref>, <tf.Tensor 'simple_rnn_1/while/Exit_3:0' shape=(1, 4) dtype=float32>)]}, '_built': True, '_inbound_nodes': [<keras.engine.base_layer.Node object at 0x7ff1e32a37b8>], '_outbound_nodes': [<keras.engine.base_layer.Node object at 0x7ff1e3285cf8>], 'name': 'simple_rnn_1', 'trainable': True, 'batch_input_shape': (1, 1, 13), 'dtype': 'float32', '_initial_weights': None, 'cell': <keras.layers.recurrent.SimpleRNNCell object at 0x7ff1e7328940>, 'return_sequences': False, 'return_state': False, 'go_backwards': False, 'unroll': False, 'state_spec': [InputSpec(shape=(None, 4), ndim=2)], '_states': [<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 4) dtype=float32_ref>], 'constants_spec': None, '_num_constants': None, 'activity_regularizer': None}
KERAS_CREATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
LAYER_CHECK_COLUMNS ('simple_rnn_1', <class 'keras.layers.recurrent.SimpleRNN'>, (1, 1, 13), 14, 14)
KERAS_GENERATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
KERAS_CREATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
LAYER_GENERATE_CODE_START simple_rnn_1 (1, 1, 13)
RNN_LAYER_INTERNAL inputs  19 ['rn_1', 'KEY', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'dot_prod_1', 'dot_prod_2', 'dot_prod_3', 'dot_prod_4']
RNN_LAYER_INTERNAL current_states  4 ['PreviousState_1', 'PreviousState_2', 'PreviousState_3', 'PreviousState_4']
RNN_LAYER_INTERNAL inputs  19 ['rn', 'KEY', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'dot_prod_1', 'dot_prod_2', 'dot_prod_3', 'dot_prod_4']
RNN_LAYER_INTERNAL current_states  4 ['PreviousState_1', 'PreviousState_2', 'PreviousState_3', 'PreviousState_4']
LAYER_GENERATE_CODE_END simple_rnn_1 (1, 4)
GENERATING_LAYER 1 dense_1 <class 'keras.layers.core.Dense'> {'input_spec': InputSpec(min_ndim=2, axes={-1: 4}), 'supports_masking': True, 'stateful': False, '_trainable_weights': [<tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32_ref>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>], '_non_trainable_weights': [], '_losses': [], '_updates': [], '_per_input_losses': {}, '_per_input_updates': {}, '_built': True, '_inbound_nodes': [<keras.engine.base_layer.Node object at 0x7ff1e3285cf8>], '_outbound_nodes': [], 'name': 'dense_1', 'trainable': True, '_initial_weights': None, 'units': 1, 'activation': <function linear at 0x7ff1f4c87a60>, 'use_bias': True, 'kernel_initializer': <keras.initializers.VarianceScaling object at 0x7ff1e3305c18>, 'bias_initializer': <keras.initializers.Zeros object at 0x7ff1e3305780>, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'kernel': <tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32_ref>, 'bias': <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>}
KERAS_CREATE_LAYER_START <class 'keras.layers.core.Dense'>
LAYER_CHECK_COLUMNS ('dense_1', <class 'keras.layers.core.Dense'>, (1, 4), 5, 5)
KERAS_GENERATE_LAYER_START <class 'keras.layers.core.Dense'>
KERAS_CREATE_LAYER_START <class 'keras.layers.core.Dense'>
LAYER_GENERATE_CODE_START dense_1 (1, 4)
LAYER_GENERATE_CODE_END dense_1 (1, 1)
KERAS_REG_CODE_GENERATION_END <class 'sqlalchemy.sql.selectable.Alias'> <class 'sklearn2sql.GenericModels.Keras.cSerializedKeras'>
TEMP_SQLS []
FINAL_SQL WITH RECURSIVE keras_input AS
(SELECT "...put_1 AS "Estimator"
FROM layer_dense_1

In [11]:
print(lSQL)

WITH RECURSIVE keras_input AS
(SELECT "ADS"."KEY" AS "KEY", "ADS"."CRIM" AS "CRIM", "ADS"."ZN" AS "ZN", "ADS"."INDUS" AS "INDUS", "ADS"."CHAS" AS "CHAS", "ADS"."NOX" AS "NOX", "ADS"."RM" AS "RM", "ADS"."AGE" AS "AGE", "ADS"."DIS" AS "DIS", "ADS"."RAD" AS "RAD", "ADS"."TAX" AS "TAX", "ADS"."PTRATIO" AS "PTRATIO", "ADS"."B" AS "B", "ADS"."LSTAT" AS "LSTAT"
FROM boston AS "ADS"),
keras_input_1 AS
(SELECT keras_input."KEY" AS "KEY", keras_input."CRIM" AS "CRIM", keras_input."ZN" AS "ZN", keras_input."INDUS" AS "INDUS", keras_input."CHAS" AS "CHAS", keras_input."NOX" AS "NOX", keras_input."RM" AS "RM", keras_input."AGE" AS "AGE", keras_input."DIS" AS "DIS", keras_input."RAD" AS "RAD", keras_input."TAX" AS "TAX", keras_input."PTRATIO" AS "PTRATIO", keras_input."B" AS "B", keras_input."LSTAT" AS "LSTAT"
FROM keras_input),
keras_input_1_rn AS
(SELECT row_number() OVER (ORDER BY keras_input_1."KEY" ASC) AS rn, keras_input_1."KEY" AS "KEY", keras_input_1."CRIM" AS "CRIM", keras_input_1."ZN" AS "ZN", keras_input_1."INDUS" AS "INDUS", keras_input_1."CHAS" AS "CHAS", keras_input_1."NOX" AS "NOX", keras_input_1."RM" AS "RM", keras_input_1."AGE" AS "AGE", keras_input_1."DIS" AS "DIS", keras_input_1."RAD" AS "RAD", keras_input_1."TAX" AS "TAX", keras_input_1."PTRATIO" AS "PTRATIO", keras_input_1."B" AS "B", keras_input_1."LSTAT" AS "LSTAT"
FROM keras_input_1),
input_kernel_bias AS
(SELECT keras_input_1_rn.rn AS rn, keras_input_1_rn."KEY" AS "KEY", keras_input_1_rn."CRIM" AS "CRIM", keras_input_1_rn."ZN" AS "ZN", keras_input_1_rn."INDUS" AS "INDUS", keras_input_1_rn."CHAS" AS "CHAS", keras_input_1_rn."NOX" AS "NOX", keras_input_1_rn."RM" AS "RM", keras_input_1_rn."AGE" AS "AGE", keras_input_1_rn."DIS" AS "DIS", keras_input_1_rn."RAD" AS "RAD", keras_input_1_rn."TAX" AS "TAX", keras_input_1_rn."PTRATIO" AS "PTRATIO", keras_input_1_rn."B" AS "B", keras_input_1_rn."LSTAT" AS "LSTAT", 0.3873119056224823 + -0.40661174058914185 * keras_input_1_rn."CRIM" + 0.13198424875736237 * keras_input_1_rn."ZN" + -0.23197950422763824 * keras_input_1_rn."INDUS" + 0.22540287673473358 * keras_input_1_rn."CHAS" + -0.34031710028648376 * keras_input_1_rn."NOX" + 1.4033734798431396 * keras_input_1_rn."RM" + -0.39703428745269775 * keras_input_1_rn."AGE" + -0.18565256893634796 * keras_input_1_rn."DIS" + -0.1275901347398758 * keras_input_1_rn."RAD" + -0.5371177792549133 * keras_input_1_rn."TAX" + -0.5878210663795471 * keras_input_1_rn."PTRATIO" + 0.23480302095413208 * keras_input_1_rn."B" + -0.8542886972427368 * keras_input_1_rn."LSTAT" AS dot_prod_1, -0.7916075587272644 + -0.06890541315078735 * keras_input_1_rn."CRIM" + 0.09522277116775513 * keras_input_1_rn."ZN" + 0.12117820978164673 * keras_input_1_rn."INDUS" + -0.19121648371219635 * keras_input_1_rn."CHAS" + -0.08015965670347214 * keras_input_1_rn."NOX" + 1.4621937274932861 * keras_input_1_rn."RM" + 0.009547353722155094 * keras_input_1_rn."AGE" + -0.4001479148864746 * keras_input_1_rn."DIS" + -0.07804850488901138 * keras_input_1_rn."RAD" + -0.5620753169059753 * keras_input_1_rn."TAX" + -0.031235458329319954 * keras_input_1_rn."PTRATIO" + -0.48043251037597656 * keras_input_1_rn."B" + -0.4698508679866791 * keras_input_1_rn."LSTAT" AS dot_prod_2, 0.9693984389305115 + -0.18505890667438507 * keras_input_1_rn."CRIM" + -0.34413814544677734 * keras_input_1_rn."ZN" + 0.7029693722724915 * keras_input_1_rn."INDUS" + 0.06874138116836548 * keras_input_1_rn."CHAS" + -0.06379007548093796 * keras_input_1_rn."NOX" + -0.13871200382709503 * keras_input_1_rn."RM" + -0.3423314392566681 * keras_input_1_rn."AGE" + -0.5773769021034241 * keras_input_1_rn."DIS" + 0.6756312847137451 * keras_input_1_rn."RAD" + 0.21186810731887817 * keras_input_1_rn."TAX" + -0.004273875616490841 * keras_input_1_rn."PTRATIO" + 0.3299005925655365 * keras_input_1_rn."B" + -0.7544145584106445 * keras_input_1_rn."LSTAT" AS dot_prod_3, 0.5030165910720825 + 0.6989611983299255 * keras_input_1_rn."CRIM" + -0.06732074171304703 * keras_input_1_rn."ZN" + 0.1536911129951477 * keras_input_1_rn."INDUS" + -0.2003178745508194 * keras_input_1_rn."CHAS" + 0.6778318285942078 * keras_input_1_rn."NOX" + 0.08071596920490265 * keras_input_1_rn."RM" + 0.7489198446273804 * keras_input_1_rn."AGE" + 0.005194464698433876 * keras_input_1_rn."DIS" + 0.28741002082824707 * keras_input_1_rn."RAD" + 0.47478365898132324 * keras_input_1_rn."TAX" + 0.3348141610622406 * keras_input_1_rn."PTRATIO" + -0.7511325478553772 * keras_input_1_rn."B" + 1.184666633605957 * keras_input_1_rn."LSTAT" AS dot_prod_4
FROM keras_input_1_rn),
rnn_cte_simple_rnn_1(rn_1, "KEY", "PreviousState_1", "PreviousState_2", "PreviousState_3", "PreviousState_4", output_1, output_2, output_3, output_4, "State_1", "State_2", "State_3", "State_4") AS
(SELECT input_kernel_bias.rn AS rn_1, input_kernel_bias."KEY" AS "KEY", CAST(0.0 AS FLOAT) AS "PreviousState_1", CAST(0.0 AS FLOAT) AS "PreviousState_2", CAST(0.0 AS FLOAT) AS "PreviousState_3", CAST(0.0 AS FLOAT) AS "PreviousState_4", greatest(input_kernel_bias.dot_prod_1 + -0.5547118186950684 * 0.0 + -0.23668420314788818 * 0.0 + 0.1634543389081955 * 0.0 + 0.2916069030761719 * 0.0, 0) AS output_1, greatest(input_kernel_bias.dot_prod_2 + 0.2081621140241623 * 0.0 + -0.5008333325386047 * 0.0 + -1.2099241018295288 * 0.0 + -1.0178906917572021 * 0.0, 0) AS output_2, greatest(input_kernel_bias.dot_prod_3 + 0.8464944958686829 * 0.0 + 0.5923721790313721 * 0.0 + -1.252794861793518 * 0.0 + -0.23256205022335052 * 0.0, 0) AS output_3, greatest(input_kernel_bias.dot_prod_4 + 0.25972887873649597 * 0.0 + 0.853052020072937 * 0.0 + -1.3105628490447998 * 0.0 + -0.8378517627716064 * 0.0, 0) AS output_4, greatest(input_kernel_bias.dot_prod_1 + -0.5547118186950684 * 0.0 + -0.23668420314788818 * 0.0 + 0.1634543389081955 * 0.0 + 0.2916069030761719 * 0.0, 0) AS "State_1", greatest(input_kernel_bias.dot_prod_2 + 0.2081621140241623 * 0.0 + -0.5008333325386047 * 0.0 + -1.2099241018295288 * 0.0 + -1.0178906917572021 * 0.0, 0) AS "State_2", greatest(input_kernel_bias.dot_prod_3 + 0.8464944958686829 * 0.0 + 0.5923721790313721 * 0.0 + -1.252794861793518 * 0.0 + -0.23256205022335052 * 0.0, 0) AS "State_3", greatest(input_kernel_bias.dot_prod_4 + 0.25972887873649597 * 0.0 + 0.853052020072937 * 0.0 + -1.3105628490447998 * 0.0 + -0.8378517627716064 * 0.0, 0) AS "State_4"
FROM input_kernel_bias
WHERE input_kernel_bias.rn = 1 UNION ALL SELECT input_kernel_bias.rn AS rn, input_kernel_bias."KEY" AS "KEY", rnn_cte_simple_rnn_1."State_1" AS "PreviousState_1", rnn_cte_simple_rnn_1."State_2" AS "PreviousState_2", rnn_cte_simple_rnn_1."State_3" AS "PreviousState_3", rnn_cte_simple_rnn_1."State_4" AS "PreviousState_4", greatest(input_kernel_bias.dot_prod_1 + -0.5547118186950684 * rnn_cte_simple_rnn_1."State_1" + -0.23668420314788818 * rnn_cte_simple_rnn_1."State_2" + 0.1634543389081955 * rnn_cte_simple_rnn_1."State_3" + 0.2916069030761719 * rnn_cte_simple_rnn_1."State_4", 0) AS output_1, greatest(input_kernel_bias.dot_prod_2 + 0.2081621140241623 * rnn_cte_simple_rnn_1."State_1" + -0.5008333325386047 * rnn_cte_simple_rnn_1."State_2" + -1.2099241018295288 * rnn_cte_simple_rnn_1."State_3" + -1.0178906917572021 * rnn_cte_simple_rnn_1."State_4", 0) AS output_2, greatest(input_kernel_bias.dot_prod_3 + 0.8464944958686829 * rnn_cte_simple_rnn_1."State_1" + 0.5923721790313721 * rnn_cte_simple_rnn_1."State_2" + -1.252794861793518 * rnn_cte_simple_rnn_1."State_3" + -0.23256205022335052 * rnn_cte_simple_rnn_1."State_4", 0) AS output_3, greatest(input_kernel_bias.dot_prod_4 + 0.25972887873649597 * rnn_cte_simple_rnn_1."State_1" + 0.853052020072937 * rnn_cte_simple_rnn_1."State_2" + -1.3105628490447998 * rnn_cte_simple_rnn_1."State_3" + -0.8378517627716064 * rnn_cte_simple_rnn_1."State_4", 0) AS output_4, greatest(input_kernel_bias.dot_prod_1 + -0.5547118186950684 * rnn_cte_simple_rnn_1."State_1" + -0.23668420314788818 * rnn_cte_simple_rnn_1."State_2" + 0.1634543389081955 * rnn_cte_simple_rnn_1."State_3" + 0.2916069030761719 * rnn_cte_simple_rnn_1."State_4", 0) AS "State_1", greatest(input_kernel_bias.dot_prod_2 + 0.2081621140241623 * rnn_cte_simple_rnn_1."State_1" + -0.5008333325386047 * rnn_cte_simple_rnn_1."State_2" + -1.2099241018295288 * rnn_cte_simple_rnn_1."State_3" + -1.0178906917572021 * rnn_cte_simple_rnn_1."State_4", 0) AS "State_2", greatest(input_kernel_bias.dot_prod_3 + 0.8464944958686829 * rnn_cte_simple_rnn_1."State_1" + 0.5923721790313721 * rnn_cte_simple_rnn_1."State_2" + -1.252794861793518 * rnn_cte_simple_rnn_1."State_3" + -0.23256205022335052 * rnn_cte_simple_rnn_1."State_4", 0) AS "State_3", greatest(input_kernel_bias.dot_prod_4 + 0.25972887873649597 * rnn_cte_simple_rnn_1."State_1" + 0.853052020072937 * rnn_cte_simple_rnn_1."State_2" + -1.3105628490447998 * rnn_cte_simple_rnn_1."State_3" + -0.8378517627716064 * rnn_cte_simple_rnn_1."State_4", 0) AS "State_4"
FROM input_kernel_bias, rnn_cte_simple_rnn_1
WHERE input_kernel_bias.rn = rnn_cte_simple_rnn_1.rn_1 + 1),
simple_rnn_1 AS
(SELECT rnn_cte_simple_rnn_1."KEY" AS "KEY", CAST(rnn_cte_simple_rnn_1.output_1 AS FLOAT) AS output_1, CAST(rnn_cte_simple_rnn_1.output_2 AS FLOAT) AS output_2, CAST(rnn_cte_simple_rnn_1.output_3 AS FLOAT) AS output_3, CAST(rnn_cte_simple_rnn_1.output_4 AS FLOAT) AS output_4
FROM rnn_cte_simple_rnn_1),
simple_rnn_1_1 AS
(SELECT simple_rnn_1."KEY" AS "KEY", simple_rnn_1.output_1 AS output_1, simple_rnn_1.output_2 AS output_2, simple_rnn_1.output_3 AS output_3, simple_rnn_1.output_4 AS output_4
FROM simple_rnn_1),
layer_dense_1 AS
(SELECT simple_rnn_1_1."KEY" AS "KEY", -0.503729522228241 + 0.24783508479595184 * simple_rnn_1_1.output_1 + 0.3189159333705902 * simple_rnn_1_1.output_2 + 0.1332019865512848 * simple_rnn_1_1.output_3 + -0.18042200803756714 * simple_rnn_1_1.output_4 AS output_1
FROM simple_rnn_1_1)
 SELECT layer_dense_1."KEY" AS "KEY", layer_dense_1.output_1 AS "Estimator"
FROM layer_dense_1

# Execute the SQL Code

In [12]:
# save the dataset in a database table


import sqlalchemy as sa

#engine = sa.create_engine('sqlite://' , echo=False)
engine = sa.create_engine("postgresql://db:db@localhost/db?port=5432", echo=False)
conn = engine.connect()

lTable = pd.DataFrame(boston.data);
lTable.columns = lMetaData['features']
lTable['TGT'] = boston.target
lTable['KEY'] = range(boston.data.shape[0])
lTable.to_sql(lMetaData['table'] , conn,   if_exists='replace', index=False)

In [13]:
sql_output = pd.read_sql(lSQL , conn);

In [14]:
sql_output.sample(12, random_state=1960)

     KEY  Estimator
230  230  -0.218930
112  112  -0.444235
125  125  -0.444980
9      9  -0.266716
213  213   0.286313
109  109  -0.503730
127  127  -0.494083
244  244  -0.503730
406  406  -0.503730
490  490  -1.362760
245  245  -0.503730
133  133  -0.503730

# Keras Prediction

In [15]:
skl_output = pd.DataFrame()
skl_output_key = pd.DataFrame(list(range(boston.data.shape[0])), columns=['KEY']);
data = boston.data.reshape(boston.data.shape[0] , 1, boston.data.shape[1])
skl_out = clf.predict(data)
print(skl_out.shape)
skl_output_estimator = pd.DataFrame(skl_out, columns=['Estimator'])
skl_output['KEY'] = skl_output_key['KEY']
skl_output['Estimator'] = skl_output_estimator
skl_output.sample(12, random_state=1960)

(506,)

     KEY  Estimator
230  230  -0.218930
112  112  -0.444235
125  125  -0.444980
9      9  -0.266716
213  213   0.286313
109  109  -0.503730
127  127  -0.494083
244  244  -0.503730
406  406  -0.503730
490  490  -1.362759
245  245  -0.503730
133  133  -0.503730

# Comparing the SQL and Keras Predictions

In [16]:
sql_skl_join = skl_output.join(sql_output , how='left', on='KEY', lsuffix='_skl', rsuffix='_sql')
sql_skl_join['Error'] = sql_skl_join.Estimator_sql - sql_skl_join.Estimator_skl

In [17]:
sql_skl_join.head(12)

    KEY_skl  Estimator_skl  KEY_sql  Estimator_sql         Error
0         0       0.624850        0       0.624850 -1.025512e-07
1         1       0.084729        1       0.084729  3.295648e-08
2         2       0.748350        2       0.748350 -5.327277e-08
3         3       1.264230        3       1.264230 -4.284777e-08
4         4       0.392285        4       0.392285 -4.750618e-08
5         5       0.349176        5       0.349176 -6.075341e-08
6         6      -0.190891        6      -0.190891  1.029333e-08
7         7      -0.664848        7      -0.664848  1.621480e-08
8         8      -0.817493        8      -0.817493 -4.275059e-08
9         9      -0.266716        9      -0.266716 -7.976741e-09
10       10      -0.648631       10      -0.648631  8.938253e-09
11       11      -0.199432       11      -0.199432 -3.257282e-08

In [18]:
sql_skl_join.describe()

          KEY_skl  Estimator_skl     KEY_sql  Estimator_sql         Error
count  506.000000     506.000000  506.000000     506.000000  5.060000e+02
mean   252.500000      -0.134431  252.500000      -0.134431  1.847776e-09
std    146.213884       0.800508  146.213884       0.800508  1.981533e-07
min      0.000000      -2.341866    0.000000      -2.341865 -2.092728e-06
25%    126.250000      -0.503730  126.250000      -0.503730 -3.220922e-08
50%    252.500000      -0.261804  252.500000      -0.261804  0.000000e+00
75%    378.750000       0.239133  378.750000       0.239133  3.512225e-08
max    505.000000       3.058708  505.000000       3.058708  8.854821e-07