In [1]:
import os, numpy as np
import pandas as pd

os.environ["KERAS_BACKEND"] = "tensorflow"

import keras 
from sklearn import datasets

from sklearn.model_selection import train_test_split

from keras.utils import np_utils


def set_reproducible():
    import tensorflow as tf
    import random as rn
    import os
    os.environ['PYTHONHASHSEED'] = '1960'
    rn.seed(1960)
    np.random.seed(1960)
    session_conf = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)

    from keras import backend as K
    tf.set_random_seed(1960)

    sess = tf.Session(graph=tf.get_default_graph(), config=session_conf)
    K.set_session(sess)

set_reproducible()

Using TensorFlow backend.

# Build a Keras Model

In [2]:
NC = 13

def create_model():
    from keras.models import Sequential
    from keras.layers import Dense, Activation, SimpleRNN
    from keras.constraints import max_norm

    model = Sequential()
    model.add(SimpleRNN(1, input_shape=(1, NC), batch_size=1 , 
                   activation='relu',
                   stateful=True,
                   kernel_constraint=max_norm(2.),
                   recurrent_constraint=max_norm(2.),
                   kernel_initializer = keras.initializers.Orthogonal(gain=0.1),
                   recurrent_initializer = keras.initializers.Zeros()))
    model.add(Dense(1, activation=None))
    adam_optimizer = keras.optimizers.Adam(lr=0.01, clipnorm=1.)
    model.compile(loss='mse', optimizer=adam_optimizer)
    return model

In [3]:
boston  = datasets.load_boston()
boston.data = (boston.data - boston.data.mean(axis=0)) / boston.data.std(axis=0)
boston.target = (boston.target - boston.target.mean(axis=0)) / boston.target.std(axis=0)

boston.data = boston.data[:,0:NC]

train_X, test_X, train_y, test_y = train_test_split(boston.data, boston.target, train_size=0.6, test_size=0.4, random_state=1960)
train_X = train_X.reshape(train_X.shape[0] , 1, train_X.shape[1])
test_X = test_X.reshape(test_X.shape[0] , 1, test_X.shape[1])

In [4]:
#boston.data

In [5]:
#boston.target

In [6]:

from keras.wrappers.scikit_learn import KerasRegressor

clf = KerasRegressor(build_fn=create_model, batch_size=1, epochs=12, verbose=2)

print(train_X.shape , train_y.shape)
clf.fit(train_X, train_y)

(303, 1, 13) (303,)
Epoch 1/12
 - 1s - loss: 0.5270
Epoch 2/12
 - 1s - loss: 0.3467
Epoch 3/12
 - 1s - loss: 0.3287
Epoch 4/12
 - 1s - loss: 0.3141
Epoch 5/12
 - 1s - loss: 0.3071
Epoch 6/12
 - 1s - loss: 0.2918
Epoch 7/12
 - 1s - loss: 0.3009
Epoch 8/12
 - 1s - loss: 0.2988
Epoch 9/12
 - 1s - loss: 0.2864
Epoch 10/12
 - 1s - loss: 0.3066
Epoch 11/12
 - 1s - loss: 0.3146
Epoch 12/12
 - 1s - loss: 0.3220

In [7]:
print(test_X.shape)
preds = clf.predict(test_X)
print(preds)

(203, 1, 13)
[ 1.57322466e-01 -3.55138779e-01  3.30862403e-02 -3.06719005e-01
  5.45046866e-01 -4.09224093e-01 -6.38198018e-01 -5.64940333e-01
 -8.75415742e-01 -8.75415742e-01 -6.94310725e-01 -4.53889102e-01
  2.68777192e-01 -8.75415742e-01  1.29493308e+00 -7.32994914e-01
  1.41234589e+00 -1.15855753e-01 -8.75415742e-01  7.73220837e-01
 -1.23791695e-01  2.02671361e+00 -8.75415742e-01  7.82700598e-01
  9.02883112e-01 -3.65100026e-01 -1.14661038e-01 -8.75415742e-01
  2.77620733e-01 -8.75415742e-01  6.09988272e-01 -8.26449454e-01
 -8.75415742e-01  1.59117198e+00  2.15869725e-01  2.27343261e-01
  5.73326886e-01 -8.75415742e-01 -1.69420123e-01  7.23636568e-01
 -7.19867229e-01  2.39722669e-01  7.43675232e-03 -8.75415742e-01
 -2.60159492e-01  7.24387765e-02  5.60655177e-01  2.41226494e-01
 -8.75415742e-01 -7.42264688e-01 -5.97059131e-01 -7.29745567e-01
 -8.75415742e-01  2.10223198e+00 -5.30124545e-01 -8.75415742e-01
  1.24317360e+00 -1.80245280e-01 -1.91910744e-01 -6.32881939e-01
 -5.36063552e-01  1.40120101e+00 -3.38351011e-01  3.49357426e-01
 -8.75415742e-01  1.38184261e+00 -6.30637646e-01 -7.82584071e-01
 -7.38293409e-01  3.29000533e-01  2.25371182e-01  1.90158963e+00
 -5.21090806e-01  1.55591309e-01  4.88038599e-01 -8.75415742e-01
  1.79732156e+00  5.45008481e-01 -8.75415742e-01  1.19373012e+00
 -8.75415742e-01  6.40352428e-01  2.19792545e-01 -8.75415742e-01
 -6.38719380e-01  1.02217770e+00 -7.32804239e-01  1.46016264e+00
 -6.30088806e-01  7.73223221e-01 -8.75415742e-01  1.18741059e+00
 -4.36822683e-01 -8.75415742e-01  3.47560227e-01  1.31810486e-01
  1.27214456e+00  7.47814476e-01 -1.41499043e-02 -3.70736659e-01
  3.46470296e-01 -3.48504186e-01  6.93716347e-01 -6.84884310e-01
  1.49462402e-01 -9.92533565e-02 -4.81872618e-01 -8.75415742e-01
  1.86981940e+00 -8.75415742e-01  1.04374671e+00 -1.89887643e-01
  1.84779823e-01  1.07713079e+00 -8.75415742e-01  4.88493741e-01
 -8.75415742e-01 -8.75415742e-01 -8.75415742e-01  5.06933391e-01
 -1.28663838e-01 -8.75415742e-01 -8.75415742e-01 -4.47222710e-01
  9.21409726e-02  1.32820225e+00 -8.75415742e-01 -2.83697844e-02
 -8.75415742e-01 -8.75415742e-01 -7.81207681e-02 -3.57851386e-02
  7.06889808e-01  4.79256809e-01 -7.31066704e-01 -6.20729625e-01
  9.80165303e-01 -3.42543960e-01  6.07663393e-02 -8.75415742e-01
 -8.75415742e-01  2.01941872e+00 -4.82753247e-01 -8.75415742e-01
  8.47184360e-01  5.33814609e-01  1.76398158e-02  2.72076905e-01
  9.96610701e-01 -4.43049192e-01 -8.75415742e-01  6.11570776e-01
  1.17264962e+00  5.14141738e-01 -8.75415742e-01 -8.75415742e-01
  2.17080259e+00 -4.14823741e-01 -8.75415742e-01 -8.75415742e-01
  8.42847288e-01 -8.75415742e-01  1.21718645e-01 -4.28012192e-01
  6.54181898e-01  2.44444191e-01 -5.24847507e-01  2.59565973e+00
 -4.44217861e-01  7.64767826e-01 -4.84557599e-01 -1.33459747e-01
 -3.15105140e-01 -8.75415742e-01 -7.62075782e-02 -8.07492733e-02
 -4.48942184e-04  3.91513705e-02  1.45485222e-01  2.84975231e-01
 -5.09131432e-01  2.33968472e+00  8.08842123e-01 -6.08453870e-01
  1.12721014e+00 -1.75058842e-04  6.00343406e-01  1.21352768e+00
 -8.75415742e-01  1.18779349e+00  1.01835012e+00  1.48920536e+00
 -8.75415742e-01 -5.53742647e-02  6.68069184e-01  1.66802239e+00
 -4.16881949e-01  7.96853602e-01  1.14903736e+00 -8.75415742e-01
 -5.30086398e-01  6.18537724e-01 -8.75415742e-01]

# Generate SQL Code from the Model

In [8]:
import json, requests, base64, dill as pickle, sys



sys.setrecursionlimit(200000)
pickle.settings['recurse'] = False

# no luck for the web service... pickling feature of tensorflow and/or keras objects seems not to be a priority.
# there is a lot of github issues in the two projects when I search for pickle keyword!!!.

def test_ws_sql_gen(pickle_data):
    WS_URL="http://localhost:1888/model"
    b64_data = base64.b64encode(pickle_data).decode('utf-8')
    data={"Name":"model1", "PickleData":b64_data , "SQLDialect":"postgresql"}
    r = requests.post(WS_URL, json=data)
    print(r.__dict__)
    content = r.json()
    # print(content)
    lSQL = content["model"]["SQLGenrationResult"][0]["SQL"]
    return lSQL;



def test_sql_gen(keras_regressor , metadata):
    import sklearn2sql.PyCodeGenerator as codegen
    cg1 = codegen.cAbstractCodeGenerator();
    cg1.mOptions.mActivateMaterialization = False
    lSQL = cg1.generateCodeWithMetadata(clf, metadata, dsn = None, dialect = "postgresql");
    return lSQL[1]

In [9]:
# commented .. see above
# pickle_data = pickle.dumps(clf)
# lSQL = test_ws_sql_gen(pickle_data)
# print(lSQL[0:2000])

In [10]:
lMetaData = {}
lMetaData['features'] = list(boston.feature_names);
lMetaData["targets"] = ['TGT']
lMetaData['primary_key'] = 'KEY'
lMetaData['table'] = 'boston'

    
lSQL = test_sql_gen(clf , lMetaData)

cGenerationWrapperFactory::createWrapper() <class 'keras.wrappers.scikit_learn.KerasRegressor'>
BACKEND_DIALECT postgresql
CREATING_DATABASE_BACKEND_DSN_DIALECT 1.2.7 None postgresql
KERAS_REG_GENERATE_EXPRESSION_START <class 'sqlalchemy.sql.selectable.Alias'> <class 'sklearn2sql.GenericModels.Keras.cSerializedKeras'>
{'mKerasData': <keras.wrappers.scikit_learn.KerasRegressor object at 0x7f793f6ee630>, 'mFeatureNames': ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'], 'mClasses': None, 'mMode': 'Regression'}
{'build_fn': <function create_model at 0x7f793f6d4950>, 'sk_params': {'batch_size': 1, 'epochs': 12, 'verbose': 2}, 'model': <keras.engine.sequential.Sequential object at 0x7f793f6ee6a0>}
GENERATING_LAYER 0 simple_rnn_1 <class 'keras.layers.recurrent.SimpleRNN'> {'input_spec': [InputSpec(shape=(1, None, 13), ndim=3)], 'supports_masking': True, 'stateful': True, '_trainable_weights': [], '_non_trainable_weights': [], '_losses': [], '_updates': [(<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 1) dtype=float32_ref>, <tf.Tensor 'simple_rnn_1/while/Exit_3:0' shape=(1, 1) dtype=float32>)], '_per_input_losses': {}, '_per_input_updates': {'140158732004152': [(<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 1) dtype=float32_ref>, <tf.Tensor 'simple_rnn_1/while/Exit_3:0' shape=(1, 1) dtype=float32>)]}, '_built': True, '_inbound_nodes': [<keras.engine.base_layer.Node object at 0x7f793b6687f0>], '_outbound_nodes': [<keras.engine.base_layer.Node object at 0x7f793b64ccf8>], 'name': 'simple_rnn_1', 'trainable': True, 'batch_input_shape': (1, 1, 13), 'dtype': 'float32', '_initial_weights': None, 'cell': <keras.layers.recurrent.SimpleRNNCell object at 0x7f793f6ee940>, 'return_sequences': False, 'return_state': False, 'go_backwards': False, 'unroll': False, 'state_spec': [InputSpec(shape=(None, 1), ndim=2)], '_states': [<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 1) dtype=float32_ref>], 'constants_spec': None, '_num_constants': None, 'activity_regularizer': None}
KERAS_CREATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
LAYER_CHECK_COLUMNS ('simple_rnn_1', <class 'keras.layers.recurrent.SimpleRNN'>, (1, 1, 13), 14, 14)
KERAS_GENERATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
KERAS_CREATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
LAYER_GENERATE_CODE_START simple_rnn_1 (1, 1, 13)
RNN_LAYER_INTERNAL inputs  16 ['rn_1', 'KEY', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'dot_prod_1']
RNN_LAYER_INTERNAL current_states  1 ['PreviousState_1']
RNN_LAYER_INTERNAL inputs  16 ['rn', 'KEY', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'dot_prod_1']
RNN_LAYER_INTERNAL current_states  1 ['PreviousState_1']
LAYER_GENERATE_CODE_END simple_rnn_1 (1, 1)
GENERATING_LAYER 1 dense_1 <class 'keras.layers.core.Dense'> {'input_spec': InputSpec(min_ndim=2, axes={-1: 1}), 'supports_masking': True, 'stateful': False, '_trainable_weights': [<tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32_ref>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>], '_non_trainable_weights': [], '_losses': [], '_updates': [], '_per_input_losses': {}, '_per_input_updates': {}, '_built': True, '_inbound_nodes': [<keras.engine.base_layer.Node object at 0x7f793b64ccf8>], '_outbound_nodes': [], 'name': 'dense_1', 'trainable': True, '_initial_weights': None, 'units': 1, 'activation': <function linear at 0x7f7944a61a60>, 'use_bias': True, 'kernel_initializer': <keras.initializers.VarianceScaling object at 0x7f793b6cac50>, 'bias_initializer': <keras.initializers.Zeros object at 0x7f793b6ca7b8>, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'kernel': <tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32_ref>, 'bias': <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>}
KERAS_CREATE_LAYER_START <class 'keras.layers.core.Dense'>
LAYER_CHECK_COLUMNS ('dense_1', <class 'keras.layers.core.Dense'>, (1, 1), 2, 2)
KERAS_GENERATE_LAYER_START <class 'keras.layers.core.Dense'>
KERAS_CREATE_LAYER_START <class 'keras.layers.core.Dense'>
LAYER_GENERATE_CODE_START dense_1 (1, 1)
LAYER_GENERATE_CODE_END dense_1 (1, 1)
KERAS_REG_CODE_GENERATION_END <class 'sqlalchemy.sql.selectable.Alias'> <class 'sklearn2sql.GenericModels.Keras.cSerializedKeras'>
TEMP_SQLS []
FINAL_SQL WITH RECURSIVE keras_input AS
(SELECT "...put_1 AS "Estimator"
FROM layer_dense_1

In [11]:
print(lSQL)

WITH RECURSIVE keras_input AS
(SELECT "ADS"."KEY" AS "KEY", "ADS"."CRIM" AS "CRIM", "ADS"."ZN" AS "ZN", "ADS"."INDUS" AS "INDUS", "ADS"."CHAS" AS "CHAS", "ADS"."NOX" AS "NOX", "ADS"."RM" AS "RM", "ADS"."AGE" AS "AGE", "ADS"."DIS" AS "DIS", "ADS"."RAD" AS "RAD", "ADS"."TAX" AS "TAX", "ADS"."PTRATIO" AS "PTRATIO", "ADS"."B" AS "B", "ADS"."LSTAT" AS "LSTAT"
FROM boston AS "ADS"),
keras_input_1 AS
(SELECT keras_input."KEY" AS "KEY", keras_input."CRIM" AS "CRIM", keras_input."ZN" AS "ZN", keras_input."INDUS" AS "INDUS", keras_input."CHAS" AS "CHAS", keras_input."NOX" AS "NOX", keras_input."RM" AS "RM", keras_input."AGE" AS "AGE", keras_input."DIS" AS "DIS", keras_input."RAD" AS "RAD", keras_input."TAX" AS "TAX", keras_input."PTRATIO" AS "PTRATIO", keras_input."B" AS "B", keras_input."LSTAT" AS "LSTAT"
FROM keras_input),
keras_input_1_rn AS
(SELECT row_number() OVER (ORDER BY keras_input_1."KEY" ASC) AS rn, keras_input_1."KEY" AS "KEY", keras_input_1."CRIM" AS "CRIM", keras_input_1."ZN" AS "ZN", keras_input_1."INDUS" AS "INDUS", keras_input_1."CHAS" AS "CHAS", keras_input_1."NOX" AS "NOX", keras_input_1."RM" AS "RM", keras_input_1."AGE" AS "AGE", keras_input_1."DIS" AS "DIS", keras_input_1."RAD" AS "RAD", keras_input_1."TAX" AS "TAX", keras_input_1."PTRATIO" AS "PTRATIO", keras_input_1."B" AS "B", keras_input_1."LSTAT" AS "LSTAT"
FROM keras_input_1),
input_kernel_bias AS
(SELECT keras_input_1_rn.rn AS rn, keras_input_1_rn."KEY" AS "KEY", keras_input_1_rn."CRIM" AS "CRIM", keras_input_1_rn."ZN" AS "ZN", keras_input_1_rn."INDUS" AS "INDUS", keras_input_1_rn."CHAS" AS "CHAS", keras_input_1_rn."NOX" AS "NOX", keras_input_1_rn."RM" AS "RM", keras_input_1_rn."AGE" AS "AGE", keras_input_1_rn."DIS" AS "DIS", keras_input_1_rn."RAD" AS "RAD", keras_input_1_rn."TAX" AS "TAX", keras_input_1_rn."PTRATIO" AS "PTRATIO", keras_input_1_rn."B" AS "B", keras_input_1_rn."LSTAT" AS "LSTAT", 1.7795400619506836 + -1.2673325538635254 * keras_input_1_rn."CRIM" + 0.02278522402048111 * keras_input_1_rn."ZN" + 0.1086830273270607 * keras_input_1_rn."INDUS" + 0.101698137819767 * keras_input_1_rn."CHAS" + -0.052447594702243805 * keras_input_1_rn."NOX" + 0.9579117894172668 * keras_input_1_rn."RM" + -0.24104787409305573 * keras_input_1_rn."AGE" + -0.266411155462265 * keras_input_1_rn."DIS" + 0.4415941834449768 * keras_input_1_rn."RAD" + -0.3148602843284607 * keras_input_1_rn."TAX" + -0.2921449542045593 * keras_input_1_rn."PTRATIO" + 0.40026164054870605 * keras_input_1_rn."B" + -0.5937979817390442 * keras_input_1_rn."LSTAT" AS dot_prod_1
FROM keras_input_1_rn),
rnn_cte_simple_rnn_1(rn_1, "KEY", "PreviousState_1", output_1, "State_1") AS
(SELECT input_kernel_bias.rn AS rn_1, input_kernel_bias."KEY" AS "KEY", CAST(0.0 AS FLOAT) AS "PreviousState_1", greatest(input_kernel_bias.dot_prod_1 + -0.2034594565629959 * 0.0, 0) AS output_1, greatest(input_kernel_bias.dot_prod_1 + -0.2034594565629959 * 0.0, 0) AS "State_1"
FROM input_kernel_bias
WHERE input_kernel_bias.rn = 1 UNION ALL SELECT input_kernel_bias.rn AS rn, input_kernel_bias."KEY" AS "KEY", rnn_cte_simple_rnn_1."State_1" AS "PreviousState_1", greatest(input_kernel_bias.dot_prod_1 + -0.2034594565629959 * rnn_cte_simple_rnn_1."State_1", 0) AS output_1, greatest(input_kernel_bias.dot_prod_1 + -0.2034594565629959 * rnn_cte_simple_rnn_1."State_1", 0) AS "State_1"
FROM input_kernel_bias, rnn_cte_simple_rnn_1
WHERE input_kernel_bias.rn = rnn_cte_simple_rnn_1.rn_1 + 1),
simple_rnn_1 AS
(SELECT rnn_cte_simple_rnn_1."KEY" AS "KEY", CAST(rnn_cte_simple_rnn_1.output_1 AS FLOAT) AS output_1
FROM rnn_cte_simple_rnn_1),
simple_rnn_1_1 AS
(SELECT simple_rnn_1."KEY" AS "KEY", simple_rnn_1.output_1 AS output_1
FROM simple_rnn_1),
layer_dense_1 AS
(SELECT simple_rnn_1_1."KEY" AS "KEY", -0.8754157423973083 + 0.5068056583404541 * simple_rnn_1_1.output_1 AS output_1
FROM simple_rnn_1_1)
 SELECT layer_dense_1."KEY" AS "KEY", layer_dense_1.output_1 AS "Estimator"
FROM layer_dense_1

# Execute the SQL Code

In [12]:
# save the dataset in a database table


import sqlalchemy as sa

#engine = sa.create_engine('sqlite://' , echo=False)
engine = sa.create_engine("postgresql://db:db@localhost/db?port=5432", echo=False)
conn = engine.connect()

lTable = pd.DataFrame(boston.data);
lTable.columns = lMetaData['features']
lTable['TGT'] = boston.target
lTable['KEY'] = range(boston.data.shape[0])
lTable.to_sql(lMetaData['table'] , conn,   if_exists='replace', index=False)

In [13]:
sql_output = pd.read_sql(lSQL , conn);

In [14]:
sql_output.sample(12, random_state=1960)

     KEY  Estimator
230  230  -0.088796
112  112  -0.428158
125  125  -0.008880
9      9  -0.121876
213  213   0.459976
109  109  -0.306147
127  127  -0.543347
244  244  -0.828347
406  406  -0.875416
490  490  -0.875416
245  245  -0.703887
133  133  -0.587732

# Keras Prediction

In [15]:
skl_output = pd.DataFrame()
skl_output_key = pd.DataFrame(list(range(boston.data.shape[0])), columns=['KEY']);
data = boston.data.reshape(boston.data.shape[0] , 1, boston.data.shape[1])
skl_out = clf.predict(data)
print(skl_out.shape)
skl_output_estimator = pd.DataFrame(skl_out, columns=['Estimator'])
skl_output['KEY'] = skl_output_key['KEY']
skl_output['Estimator'] = skl_output_estimator
skl_output.sample(12, random_state=1960)

(506,)

     KEY  Estimator
230  230  -0.088796
112  112  -0.428158
125  125  -0.008880
9      9  -0.121876
213  213   0.459976
109  109  -0.306147
127  127  -0.543347
244  244  -0.828347
406  406  -0.875416
490  490  -0.875416
245  245  -0.703887
133  133  -0.587732

# Comparing the SQL and Keras Predictions

In [16]:
sql_skl_join = skl_output.join(sql_output , how='left', on='KEY', lsuffix='_skl', rsuffix='_sql')
sql_skl_join['Error'] = sql_skl_join.Estimator_sql - sql_skl_join.Estimator_skl

In [17]:
sql_skl_join.head(12)

    KEY_skl  Estimator_skl  KEY_sql  Estimator_sql         Error
0         0       0.929029        0       0.929029 -5.378071e-08
1         1       0.113459        1       0.113459  1.334226e-08
2         2       1.091642        2       1.091641 -2.715767e-07
3         3       0.755365        3       0.755365  1.021069e-07
4         4       0.791832        4       0.791832  3.515764e-08
5         5       0.270771        5       0.270771  1.105575e-09
6         6       0.023396        6       0.023396  1.382971e-07
7         7      -0.253590        7      -0.253590 -2.313976e-08
8         8      -0.875416        8      -0.875416  3.330669e-16
9         9      -0.121876        9      -0.121876 -1.845071e-08
10       10      -0.170447       10      -0.170447  1.157720e-07
11       11      -0.037204       11      -0.037204 -5.596786e-08

In [18]:
sql_skl_join.describe()

          KEY_skl  Estimator_skl     KEY_sql  Estimator_sql         Error
count  506.000000     506.000000  506.000000     506.000000  5.060000e+02
mean   252.500000       0.029686  252.500000       0.029686  1.385797e-08
std    146.213884       0.728562  146.213884       0.728562  7.817812e-08
min      0.000000      -0.875416    0.000000      -0.875416 -2.715767e-07
25%    126.250000      -0.591632  126.250000      -0.591632 -1.805192e-08
50%    252.500000      -0.036797  252.500000      -0.036797  3.330669e-16
75%    378.750000       0.521485  378.750000       0.521485  4.656410e-08
max    505.000000       2.213554  505.000000       2.213554  6.024150e-07