In [1]:
import os, numpy as np
import pandas as pd

os.environ["KERAS_BACKEND"] = "tensorflow"

import keras 
from sklearn import datasets

from sklearn.model_selection import train_test_split

from keras.utils import np_utils


def set_reproducible():
    import tensorflow as tf
    import random as rn
    import os
    os.environ['PYTHONHASHSEED'] = '1960'
    rn.seed(1960)
    np.random.seed(1960)
    session_conf = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)

    from keras import backend as K
    tf.set_random_seed(1960)

    sess = tf.Session(graph=tf.get_default_graph(), config=session_conf)
    K.set_session(sess)

set_reproducible()

Using TensorFlow backend.
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)

# Build a Keras Model

In [2]:
NC = 13

def create_model():
    from keras.models import Sequential
    from keras.layers import Dense, Activation, SimpleRNN

    model = Sequential()
    model.add(SimpleRNN(3, input_shape=(1, NC), batch_size=1 , stateful=True))
    model.add(Dense(1))
    model.compile(optimizer='rmsprop', loss='mse')
    return model

In [3]:
boston  = datasets.load_boston()
train_X, test_X, train_y, test_y = train_test_split(boston.data, boston.target, train_size=0.6, test_size=0.4, random_state=1960)
train_X = train_X.reshape(train_X.shape[0] , 1, train_X.shape[1])
test_X = test_X.reshape(test_X.shape[0] , 1, test_X.shape[1])

In [4]:
#boston.data

In [5]:
#boston.target

In [6]:

from keras.wrappers.scikit_learn import KerasRegressor

clf = KerasRegressor(build_fn=create_model, batch_size=1, epochs=12, verbose=2)

print(train_X.shape , train_y.shape)
clf.fit(train_X, train_y)

(303, 1, 13) (303,)
SIMPLERNNCELL_CALL_IN Tensor("simple_rnn_1/strided_slice_1:0", shape=(1, 13), dtype=float32) [<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 3) dtype=float32_ref>]
SIMPLERNNCELL_CALL_OUT Tensor("simple_rnn_1/Tanh:0", shape=(1, 3), dtype=float32) [<tf.Tensor 'simple_rnn_1/Tanh:0' shape=(1, 3) dtype=float32>]
SIMPLERNNCELL_CALL_IN Tensor("simple_rnn_1/while/TensorArrayReadV3:0", shape=(1, 13), dtype=float32) (<tf.Tensor 'simple_rnn_1/while/Identity_2:0' shape=(1, 3) dtype=float32>,)
SIMPLERNNCELL_CALL_OUT Tensor("simple_rnn_1/while/Tanh:0", shape=(1, 3), dtype=float32) [<tf.Tensor 'simple_rnn_1/while/Tanh:0' shape=(1, 3) dtype=float32>]
RNN_LAYER_CALL_IN Tensor("simple_rnn_1_input:0", shape=(1, 1, 13), dtype=float32) [<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 3) dtype=float32_ref>]
RNN_LAYER_CALL_OUT Tensor("simple_rnn_1/TensorArrayReadV3:0", shape=(1, 3), dtype=float32) (<tf.Tensor 'simple_rnn_1/while/Exit_2:0' shape=(1, 3) dtype=float32>,)
Epoch 1/12
 - 1s - loss: 613.3924
Epoch 2/12
 - 0s - loss: 571.3568
Epoch 3/12
 - 0s - loss: 530.5643
Epoch 4/12
 - 0s - loss: 492.1889
Epoch 5/12
 - 0s - loss: 451.7092
Epoch 6/12
 - 0s - loss: 408.7775
Epoch 7/12
 - 0s - loss: 371.4779
Epoch 8/12
 - 0s - loss: 337.6705
Epoch 9/12
 - 0s - loss: 305.7506
Epoch 10/12
 - 0s - loss: 276.7474
Epoch 11/12
 - 0s - loss: 250.7346
Epoch 12/12
 - 0s - loss: 226.3306

In [7]:
print(test_X.shape)
preds = clf.predict(test_X)
print(preds)

(203, 1, 13)
[11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065  6.3539305 11.2611065
 11.2611065 11.2611065 11.2611065  6.3539305 11.2611065 11.2611065
 11.2611065 11.2611065  6.3539305 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065  6.3539305 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065  6.3539305 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
  6.3539305 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065  6.3539305 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
  6.3539305 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065  6.3539305 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.246108  11.2611065
 11.2611065  6.3539305 11.2611065 11.2611065 11.2611065 11.2611065
  6.3539305 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065  6.3539305 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065  6.3539305
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065
 11.2611065 11.2611065 11.2611065 11.2611065 11.2611065]

# Generate SQL Code from the Model

In [8]:
import json, requests, base64, dill as pickle, sys



sys.setrecursionlimit(200000)
pickle.settings['recurse'] = False

# no luck for the web service... pickling feature of tensorflow and/or keras objects seems not to be a priority.
# there is a lot of github issues in the two projects when I search for pickle keyword!!!.

def test_ws_sql_gen(pickle_data):
    WS_URL="http://localhost:1888/model"
    b64_data = base64.b64encode(pickle_data).decode('utf-8')
    data={"Name":"model1", "PickleData":b64_data , "SQLDialect":"postgresql"}
    r = requests.post(WS_URL, json=data)
    print(r.__dict__)
    content = r.json()
    # print(content)
    lSQL = content["model"]["SQLGenrationResult"][0]["SQL"]
    return lSQL;



def test_sql_gen(keras_regressor , metadata):
    import sklearn2sql.PyCodeGenerator as codegen
    cg1 = codegen.cAbstractCodeGenerator();
    cg1.mOptions.mActivateMaterialization = False
    lSQL = cg1.generateCodeWithMetadata(clf, metadata, dsn = None, dialect = "postgresql");
    return lSQL[1]

In [9]:
# commented .. see above
# pickle_data = pickle.dumps(clf)
# lSQL = test_ws_sql_gen(pickle_data)
# print(lSQL[0:2000])

In [10]:
lMetaData = {}
lMetaData['features'] = list(boston.feature_names);
lMetaData["targets"] = ['TGT']
lMetaData['primary_key'] = 'KEY'
lMetaData['table'] = 'boston'

    
lSQL = test_sql_gen(clf , lMetaData)

cGenerationWrapperFactory::createWrapper() <class 'keras.wrappers.scikit_learn.KerasRegressor'>
BACKEND_DIALECT postgresql
CREATING_DATABASE_BACKEND_DSN_DIALECT 1.2.7 None postgresql
KERAS_REG_GENERATE_EXPRESSION_START <class 'sqlalchemy.sql.selectable.Alias'> <class 'sklearn2sql.GenericModels.Keras.cSerializedKeras'>
{'mKerasData': <keras.wrappers.scikit_learn.KerasRegressor object at 0x7f2a7b4df128>, 'mFeatureNames': ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'], 'mClasses': None, 'mMode': 'Regression'}
{'build_fn': <function create_model at 0x7f2a7b4d41e0>, 'sk_params': {'batch_size': 1, 'epochs': 12, 'verbose': 2}, 'model': <keras.models.Sequential object at 0x7f2a7b4df0f0>}
ABSTRACT_GENERATE_CTE keras_input keras_input 14 False False
ABSTRACT_GENERATE_SIMPLE_CTE keras_input 14
GENERATING_LAYER 0 simple_rnn_1 <class 'keras.layers.recurrent.SimpleRNN'> {'input_spec': [InputSpec(shape=(1, None, 13), ndim=3)], 'supports_masking': True, 'stateful': True, '_trainable_weights': [], '_non_trainable_weights': [], '_losses': [], '_updates': [(<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 3) dtype=float32_ref>, <tf.Tensor 'simple_rnn_1/while/Exit_2:0' shape=(1, 3) dtype=float32>)], '_per_input_losses': {}, '_per_input_updates': {'139820434062920': [(<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 3) dtype=float32_ref>, <tf.Tensor 'simple_rnn_1/while/Exit_2:0' shape=(1, 3) dtype=float32>)]}, '_built': True, '_inbound_nodes': [<keras.engine.topology.Node object at 0x7f2a7348c710>], '_outbound_nodes': [<keras.engine.topology.Node object at 0x7f2a734020f0>], 'name': 'simple_rnn_1', 'trainable': True, 'batch_input_shape': (1, 1, 13), 'dtype': 'float32', '_initial_weights': None, 'cell': <keras.layers.recurrent.SimpleRNNCell object at 0x7f2a7b4df2b0>, 'return_sequences': False, 'return_state': False, 'go_backwards': False, 'unroll': False, 'state_spec': [InputSpec(shape=(None, 3), ndim=2)], '_states': [<tf.Variable 'simple_rnn_1/Variable:0' shape=(1, 3) dtype=float32_ref>], 'constants_spec': None, '_num_constants': None, 'activity_regularizer': None}
<class 'sqlalchemy.sql.selectable.CTE'>
ABSTRACT_GENERATE_CTE keras_input keras_input_1 14 False False
ABSTRACT_GENERATE_SIMPLE_CTE keras_input_1 14
KERAS_GENERATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
KERAS_CREATE_LAYER_START <class 'keras.layers.recurrent.SimpleRNN'>
ABSTRACT_GENERATE_CTE keras_input_1_rn keras_input_1_rn 15 False False
ABSTRACT_GENERATE_SIMPLE_CTE keras_input_1_rn 15
ABSTRACT_GENERATE_CTE input_kernel_bias input_kernel_bias 18 False False
ABSTRACT_GENERATE_SIMPLE_CTE input_kernel_bias 18
GENERATE_ACTIVATION_FUNCTION_ONE_COLUMN tanh output_1
GENERATE_ACTIVATION_FUNCTION_ONE_COLUMN tanh output_2
GENERATE_ACTIVATION_FUNCTION_ONE_COLUMN tanh output_3
GENERATE_ACTIVATION_FUNCTION_ONE_COLUMN tanh output_1
GENERATE_ACTIVATION_FUNCTION_ONE_COLUMN tanh output_2
GENERATE_ACTIVATION_FUNCTION_ONE_COLUMN tanh output_3
ABSTRACT_GENERATE_CTE simple_rnn_1 simple_rnn_1 4 False False
ABSTRACT_GENERATE_SIMPLE_CTE simple_rnn_1 4
GENERATING_LAYER 1 dense_1 <class 'keras.layers.core.Dense'> {'input_spec': InputSpec(min_ndim=2, axes={-1: 3}), 'supports_masking': True, 'stateful': False, '_trainable_weights': [<tf.Variable 'dense_1/kernel:0' shape=(3, 1) dtype=float32_ref>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>], '_non_trainable_weights': [], '_losses': [], '_updates': [], '_per_input_losses': {}, '_per_input_updates': {}, '_built': True, '_inbound_nodes': [<keras.engine.topology.Node object at 0x7f2a734020f0>], '_outbound_nodes': [], 'name': 'dense_1', 'trainable': True, '_initial_weights': None, 'units': 1, 'activation': <function linear at 0x7f2a847ea8c8>, 'use_bias': True, 'kernel_initializer': <keras.initializers.VarianceScaling object at 0x7f2a73467748>, 'bias_initializer': <keras.initializers.Zeros object at 0x7f2a73422cf8>, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'kernel': <tf.Variable 'dense_1/kernel:0' shape=(3, 1) dtype=float32_ref>, 'bias': <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>}
<class 'sqlalchemy.sql.selectable.CTE'>
ABSTRACT_GENERATE_CTE simple_rnn_1 simple_rnn_1_1 4 False False
ABSTRACT_GENERATE_SIMPLE_CTE simple_rnn_1_1 4
KERAS_GENERATE_LAYER_START <class 'keras.layers.core.Dense'>
KERAS_CREATE_LAYER_START <class 'keras.layers.core.Dense'>
ABSTRACT_GENERATE_CTE layer_dense_1 layer_dense_1 2 False False
ABSTRACT_GENERATE_SIMPLE_CTE layer_dense_1 2
GENERATE_ACTIVATION_FUNCTION linear
KERAS_REG_CODE_GENERATION_END <class 'sqlalchemy.sql.selectable.Alias'> <class 'sklearn2sql.GenericModels.Keras.cSerializedKeras'>
DUMP_RESULT_CLASSES : []
DUMP_RESULT_KEY_EXPRESSIONS : ['KEY']
DUMP_RESULT_DECISION_EXPRESSION : None
DUMP_RESULT_DECISION_PROBABILITY_EXPRESSION : None
DUMP_RESULT_REG_EXPRESSIONS : {'Estimator': <sqlalchemy.sql.elements.Label object at 0x7f2a69fb1278>}
DUMP_RESULT_FEATURE_EXPRESSIONS : 0
DUMP_TEMP_TABLES : []
TEMP_SQLS []
FINAL_SQL WITH RECURSIVE keras_input AS
(SELECT "...put_1 AS "Estimator"
FROM layer_dense_1

In [11]:
print(lSQL)

WITH RECURSIVE keras_input AS
(SELECT "ADS"."KEY" AS "KEY", "ADS"."CRIM" AS "CRIM", "ADS"."ZN" AS "ZN", "ADS"."INDUS" AS "INDUS", "ADS"."CHAS" AS "CHAS", "ADS"."NOX" AS "NOX", "ADS"."RM" AS "RM", "ADS"."AGE" AS "AGE", "ADS"."DIS" AS "DIS", "ADS"."RAD" AS "RAD", "ADS"."TAX" AS "TAX", "ADS"."PTRATIO" AS "PTRATIO", "ADS"."B" AS "B", "ADS"."LSTAT" AS "LSTAT"
FROM boston AS "ADS"),
keras_input_1 AS
(SELECT keras_input."KEY" AS "KEY", keras_input."CRIM" AS "CRIM", keras_input."ZN" AS "ZN", keras_input."INDUS" AS "INDUS", keras_input."CHAS" AS "CHAS", keras_input."NOX" AS "NOX", keras_input."RM" AS "RM", keras_input."AGE" AS "AGE", keras_input."DIS" AS "DIS", keras_input."RAD" AS "RAD", keras_input."TAX" AS "TAX", keras_input."PTRATIO" AS "PTRATIO", keras_input."B" AS "B", keras_input."LSTAT" AS "LSTAT"
FROM keras_input),
keras_input_1_rn AS
(SELECT row_number() OVER (ORDER BY keras_input_1."KEY" ASC) AS rn, keras_input_1."KEY" AS "KEY", keras_input_1."CRIM" AS "CRIM", keras_input_1."ZN" AS "ZN", keras_input_1."INDUS" AS "INDUS", keras_input_1."CHAS" AS "CHAS", keras_input_1."NOX" AS "NOX", keras_input_1."RM" AS "RM", keras_input_1."AGE" AS "AGE", keras_input_1."DIS" AS "DIS", keras_input_1."RAD" AS "RAD", keras_input_1."TAX" AS "TAX", keras_input_1."PTRATIO" AS "PTRATIO", keras_input_1."B" AS "B", keras_input_1."LSTAT" AS "LSTAT"
FROM keras_input_1),
input_kernel_bias AS
(SELECT keras_input_1_rn.rn AS rn, keras_input_1_rn."KEY" AS "KEY", keras_input_1_rn."CRIM" AS "CRIM", keras_input_1_rn."ZN" AS "ZN", keras_input_1_rn."INDUS" AS "INDUS", keras_input_1_rn."CHAS" AS "CHAS", keras_input_1_rn."NOX" AS "NOX", keras_input_1_rn."RM" AS "RM", keras_input_1_rn."AGE" AS "AGE", keras_input_1_rn."DIS" AS "DIS", keras_input_1_rn."RAD" AS "RAD", keras_input_1_rn."TAX" AS "TAX", keras_input_1_rn."PTRATIO" AS "PTRATIO", keras_input_1_rn."B" AS "B", keras_input_1_rn."LSTAT" AS "LSTAT", -0.1526474803686142 + -0.07609600573778152 * keras_input_1_rn."CRIM" + -0.04115665704011917 * keras_input_1_rn."ZN" + -0.16246578097343445 * keras_input_1_rn."INDUS" + 0.11817125976085663 * keras_input_1_rn."CHAS" + -0.22861920297145844 * keras_input_1_rn."NOX" + -0.4978691637516022 * keras_input_1_rn."RM" + 0.26714715361595154 * keras_input_1_rn."AGE" + -0.23344437777996063 * keras_input_1_rn."DIS" + -0.37154486775398254 * keras_input_1_rn."RAD" + 0.13552315533161163 * keras_input_1_rn."TAX" + -0.244401752948761 * keras_input_1_rn."PTRATIO" + -0.4090282618999481 * keras_input_1_rn."B" + -0.036395084112882614 * keras_input_1_rn."LSTAT" AS dot_prod_1, 0.0 + 0.1661962866783142 * keras_input_1_rn."CRIM" + 0.09738326072692871 * keras_input_1_rn."ZN" + -0.18801289796829224 * keras_input_1_rn."INDUS" + 0.44377070665359497 * keras_input_1_rn."CHAS" + -0.49438074231147766 * keras_input_1_rn."NOX" + 0.5940975546836853 * keras_input_1_rn."RM" + -0.14400193095207214 * keras_input_1_rn."AGE" + 0.5196391940116882 * keras_input_1_rn."DIS" + -0.08744961023330688 * keras_input_1_rn."RAD" + 0.3087066411972046 * keras_input_1_rn."TAX" + 0.255348265171051 * keras_input_1_rn."PTRATIO" + -0.0731934905052185 * keras_input_1_rn."B" + 0.34239959716796875 * keras_input_1_rn."LSTAT" AS dot_prod_2, 0.0 + -0.03524869680404663 * keras_input_1_rn."CRIM" + 0.39412933588027954 * keras_input_1_rn."ZN" + 0.20680874586105347 * keras_input_1_rn."INDUS" + -0.20028209686279297 * keras_input_1_rn."CHAS" + -0.4099527597427368 * keras_input_1_rn."NOX" + -0.41654878854751587 * keras_input_1_rn."RM" + -0.5328968167304993 * keras_input_1_rn."AGE" + 0.5520102381706238 * keras_input_1_rn."DIS" + -0.5709446668624878 * keras_input_1_rn."RAD" + -0.2293562889099121 * keras_input_1_rn."TAX" + -0.0009045004844665527 * keras_input_1_rn."PTRATIO" + -0.31112179160118103 * keras_input_1_rn."B" + 0.18181532621383667 * keras_input_1_rn."LSTAT" AS dot_prod_3
FROM keras_input_1_rn),
rnn_cte_simple_rnn_1(rn_1, "KEY", "PreviousState_1", "PreviousState_2", "PreviousState_3", output_1, output_2, output_3, "State_1", "State_2", "State_3") AS
(SELECT input_kernel_bias.rn AS rn_1, input_kernel_bias."KEY" AS "KEY", CAST(0.0 AS FLOAT) AS "PreviousState_1", CAST(0.0 AS FLOAT) AS "PreviousState_2", CAST(0.0 AS FLOAT) AS "PreviousState_3", (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0) - exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0))) / (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0) + exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0))) AS output_1, (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0) - exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0))) / (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0) + exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0))) AS output_2, (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0) - exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0))) / (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0) + exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0))) AS output_3, (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0) - exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0))) / (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0) + exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * 0.0 + 0.016057631000876427 * 0.0 + 0.6978268623352051 * 0.0))) AS "State_1", (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0) - exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0))) / (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0) + exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * 0.0 + -0.9468122720718384 * 0.0 + 0.32092922925949097 * 0.0))) AS "State_2", (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0) - exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0))) / (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0) + exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * 0.0 + 0.27593860030174255 * 0.0 + 0.7722214460372925 * 0.0))) AS "State_3"
FROM input_kernel_bias
WHERE input_kernel_bias.rn = 1 UNION ALL SELECT input_kernel_bias.rn AS rn, input_kernel_bias."KEY" AS "KEY", rnn_cte_simple_rnn_1."State_1" AS "PreviousState_1", rnn_cte_simple_rnn_1."State_2" AS "PreviousState_2", rnn_cte_simple_rnn_1."State_3" AS "PreviousState_3", (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3") - exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3"))) / (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3") + exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3"))) AS output_1, (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3") - exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3"))) / (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3") + exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3"))) AS output_2, (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3") - exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3"))) / (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3") + exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3"))) AS output_3, (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3") - exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3"))) / (exp(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3") + exp(-(input_kernel_bias.dot_prod_1 + -0.7419068813323975 * rnn_cte_simple_rnn_1."State_1" + 0.016057631000876427 * rnn_cte_simple_rnn_1."State_2" + 0.6978268623352051 * rnn_cte_simple_rnn_1."State_3"))) AS "State_1", (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3") - exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3"))) / (exp(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3") + exp(-(input_kernel_bias.dot_prod_2 + 0.023472845554351807 * rnn_cte_simple_rnn_1."State_1" + -0.9468122720718384 * rnn_cte_simple_rnn_1."State_2" + 0.32092922925949097 * rnn_cte_simple_rnn_1."State_3"))) AS "State_2", (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3") - exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3"))) / (exp(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3") + exp(-(input_kernel_bias.dot_prod_3 + 0.5723040699958801 * rnn_cte_simple_rnn_1."State_1" + 0.27593860030174255 * rnn_cte_simple_rnn_1."State_2" + 0.7722214460372925 * rnn_cte_simple_rnn_1."State_3"))) AS "State_3"
FROM input_kernel_bias, rnn_cte_simple_rnn_1
WHERE input_kernel_bias.rn = rnn_cte_simple_rnn_1.rn_1 + 1),
simple_rnn_1 AS
(SELECT rnn_cte_simple_rnn_1."KEY" AS "KEY", CAST(rnn_cte_simple_rnn_1.output_1 AS FLOAT) AS output_1, CAST(rnn_cte_simple_rnn_1.output_2 AS FLOAT) AS output_2, CAST(rnn_cte_simple_rnn_1.output_3 AS FLOAT) AS output_3
FROM rnn_cte_simple_rnn_1),
simple_rnn_1_1 AS
(SELECT simple_rnn_1."KEY" AS "KEY", simple_rnn_1.output_1 AS output_1, simple_rnn_1.output_2 AS output_2, simple_rnn_1.output_3 AS output_3
FROM simple_rnn_1),
layer_dense_1 AS
(SELECT simple_rnn_1_1."KEY" AS "KEY", 3.2233598232269287 + -2.453587770462036 * simple_rnn_1_1.output_1 + 3.02994966506958 * simple_rnn_1_1.output_2 + -2.554208755493164 * simple_rnn_1_1.output_3 AS output_1
FROM simple_rnn_1_1)
 SELECT layer_dense_1."KEY" AS "KEY", layer_dense_1.output_1 AS "Estimator"
FROM layer_dense_1

# Execute the SQL Code

In [12]:
# save the dataset in a database table


import sqlalchemy as sa

#engine = sa.create_engine('sqlite://' , echo=False)
engine = sa.create_engine("postgresql://db:db@localhost/db?port=5432", echo=False)
conn = engine.connect()

lTable = pd.DataFrame(boston.data);
lTable.columns = lMetaData['features']
lTable['TGT'] = boston.target
lTable['KEY'] = range(boston.data.shape[0])
lTable.to_sql(lMetaData['table'] , conn,   if_exists='replace', index=False)

In [13]:
sql_output = pd.read_sql(lSQL , conn);

In [14]:
sql_output.sample(12, random_state=1960)

     KEY  Estimator
230  230  11.261106
112  112  11.261106
125  125  11.261106
9      9  11.261106
213  213  11.261106
109  109  11.261106
127  127  11.261106
244  244  11.261106
406  406  11.261106
490  490  11.261106
245  245  11.261106
133  133  11.261106

# Keras Prediction

In [15]:
skl_output = pd.DataFrame()
skl_output_key = pd.DataFrame(list(range(boston.data.shape[0])), columns=['KEY']);
data = boston.data.reshape(boston.data.shape[0] , 1, boston.data.shape[1])
skl_out = clf.predict(data)
print(skl_out.shape)
skl_output_estimator = pd.DataFrame(skl_out, columns=['Estimator'])
skl_output['KEY'] = skl_output_key['KEY']
skl_output['Estimator'] = skl_output_estimator
skl_output.sample(12, random_state=1960)

(506,)

     KEY  Estimator
230  230  11.261106
112  112  11.261106
125  125  11.261106
9      9  11.261106
213  213  11.261106
109  109  11.261106
127  127  11.261106
244  244  11.261106
406  406  11.261106
490  490  11.261106
245  245  11.261106
133  133  11.261106

# Comparing the SQL and Keras Predictions

In [16]:
sql_skl_join = skl_output.join(sql_output , how='left', on='KEY', lsuffix='_skl', rsuffix='_sql')
sql_skl_join['Error'] = sql_skl_join.Estimator_sql - sql_skl_join.Estimator_skl

In [17]:
sql_skl_join.head(12)

    KEY_skl  Estimator_skl  KEY_sql  Estimator_sql         Error
0         0      11.261106        0      11.261106 -4.768372e-07
1         1      11.261106        1      11.261106 -4.768372e-07
2         2      11.261106        2      11.261106 -4.768372e-07
3         3      11.261106        3      11.261106 -4.768372e-07
4         4      11.261106        4      11.261106 -4.768372e-07
5         5      11.261106        5      11.261106 -4.768372e-07
6         6      11.261106        6      11.261106 -4.768372e-07
7         7      11.261106        7      11.261106 -4.768372e-07
8         8      11.261106        8      11.261106 -4.768372e-07
9         9      11.261106        9      11.261106 -4.768372e-07
10       10      11.261106       10      11.261106 -4.768372e-07
11       11      11.261106       11      11.261106 -4.768372e-07

In [18]:
sql_skl_join.describe()

          KEY_skl  Estimator_skl     KEY_sql  Estimator_sql         Error
count  506.000000     506.000000  506.000000     506.000000  5.060000e+02
mean   252.500000      10.890812  252.500000      10.890810 -4.366978e-07
std    146.213884       1.294657  146.213884       1.294657  1.628615e-07
min      0.000000       6.353930    0.000000       6.353930 -6.318834e-07
25%    126.250000      11.261106  126.250000      11.261106 -4.768372e-07
50%    252.500000      11.261106  252.500000      11.261106 -4.768372e-07
75%    378.750000      11.261106  378.750000      11.261106 -4.768372e-07
max    505.000000      11.261106  505.000000      11.261106  1.887935e-06